image: Visual Studio 2019  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - main  # ветка git
    - dev-branch

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build:dev   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
